name: Lint

on:
  push:
    branches: [main, develop, new-features]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:  # Allows manual triggering from Actions tab

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort mypy build twine

      - name: Lint with black
        run: black --check --diff strands_agent_factory/ tests/

      - name: Sort imports with isort
        run: isort --check-only --diff strands_agent_factory/ tests/

      - name: Type check with mypy
        # Continue on error - mypy has known issues that need to be addressed
        continue-on-error: true
        run: mypy strands_agent_factory/

      - name: Build package
        run: python -m build

      - name: Check package metadata
        run: twine check dist/*
